from pathlib import Path
from datetime import date
import os
import json
import urllib.request
import urllib.parse
import xml.etree.ElementTree as ET
import sqlite3
import sys

try:
    from agents.note_policy import frontmatter, latest_note_name
except ModuleNotFoundError:
    from note_policy import frontmatter, latest_note_name

TODAY = date.today().isoformat()
VAULT = Path(os.getenv("OBSIDIAN_VAULT", str(Path.home() / "vault"))).expanduser()
OUT_DIR = VAULT / "Agentic OS" / "Daily Briefings"
OUT_DIR.mkdir(parents=True, exist_ok=True)
DB = Path("data/db/agent_os.sqlite")

CRYPTO_URL = "https://api.coingecko.com/api/v3/simple/price?ids=bitcoin,ethereum,solana&vs_currencies=usd&include_24hr_change=true"
NEWS_QUERIES = {
    "AI News": "artificial intelligence open source local LLM",
    "Linux / Software": "Linux Mint Ubuntu open source software",
    "Crypto News": "Bitcoin Ethereum crypto market",
}

def fetch_url(url, timeout=12):
    req = urllib.request.Request(url, headers={"User-Agent": "AgenticOS-Layer2/0.2"})
    with urllib.request.urlopen(req, timeout=timeout) as response:
        return response.read()

def get_crypto():
    try:
        raw = fetch_url(CRYPTO_URL)
        data = json.loads(raw.decode("utf-8"))
        rows = []
        for coin, label in [("bitcoin", "Bitcoin"), ("ethereum", "Ethereum"), ("solana", "Solana")]:
            info = data.get(coin, {})
            price = info.get("usd")
            change = info.get("usd_24h_change")
            if price is None:
                rows.append(f"- **{label}:** unavailable")
            elif change is None:
                rows.append(f"- **{label}:** ${price:,.2f}")
            else:
                rows.append(f"- **{label}:** ${price:,.2f} ({change:+.2f}% 24h)")
        return rows
    except Exception as e:
        return [f"- Crypto fetch failed: `{e}`"]

def google_news_rss(query):
    encoded = urllib.parse.quote_plus(query)
    return f"https://news.google.com/rss/search?q={encoded}&hl=en-US&gl=US&ceid=US:en"

def get_news_items(query, limit=5):
    try:
        raw = fetch_url(google_news_rss(query))
        root = ET.fromstring(raw)
        items = []
        for item in root.findall(".//item")[:limit]:
            title = item.findtext("title", default="Untitled").strip()
            link = item.findtext("link", default="").strip()
            source = item.findtext("source", default="").strip()
            pub_date = item.findtext("pubDate", default="").strip()
            display = f"- [{title}]({link})"
            if source:
                display += f" — {source}"
            if pub_date:
                display += f"  \n  Published: {pub_date}"
            items.append(display)
        return items or ["- No items found."]
    except Exception as e:
        return [f"- News fetch failed: `{e}`"]

def get_agentos_status():
    lines = []
    if DB.exists():
        try:
            with sqlite3.connect(DB) as con:
                file_count = con.execute("SELECT COUNT(*) FROM files").fetchone()[0]
                lesson_count = con.execute("SELECT COUNT(*) FROM lessons").fetchone()[0]
                research_count = con.execute("SELECT COUNT(*) FROM research_sources").fetchone()[0]
            lines += [
                f"- Indexed files in database: **{file_count}**",
                f"- Lessons stored: **{lesson_count}**",
                f"- Research notes indexed: **{research_count}**",
            ]
        except Exception as e:
            lines.append(f"- Database exists, but status check failed: `{e}`")
    else:
        lines.append("- Database not found yet.")
    for label, rel in [("File Butler dry-run notes", "File Plans"), ("Memory digests", "Memory Digests")]:
        d = VAULT / "Agentic OS" / rel
        lines.append(f"- {label}: **{len(list(d.glob('*.md'))) if d.exists() else 0}**")
    return lines

def write_briefing():
    out = OUT_DIR / f"{TODAY} READ-ME Daily Briefing.md"
    latest = OUT_DIR / latest_note_name("READ-ME", "Daily Briefing")
    lines = [
        *frontmatter(
            title=f"READ-ME: Daily Briefing - {TODAY}",
            audience="human",
            tags=["agentic-os", "daily-briefing", "read-me"],
            purpose="Readable daily snapshot for Lakota with links, status, and safe next actions.",
        ),
        "",
        f"# READ-ME: Daily Briefing - {TODAY}",
        "",
        "## Quick Summary",
        "",
        "- Generated by AgenticOS Daily Briefing Agent.",
        "- Uses free public sources and saves into Obsidian.",
        "- Treat links as a starting point, not final truth.",
        "",
        "## Crypto Snapshot",
        "",
        *get_crypto(),
        "",
        "## AI News",
        "",
        *get_news_items(NEWS_QUERIES["AI News"]),
        "",
        "## Linux / Software News",
        "",
        *get_news_items(NEWS_QUERIES["Linux / Software"]),
        "",
        "## Crypto News",
        "",
        *get_news_items(NEWS_QUERIES["Crypto News"]),
        "",
        "## AgenticOS Status",
        "",
        *get_agentos_status(),
        "",
        "## Suggested Next Actions",
        "",
        "- Review today's File Butler dry-run note.",
        "- Add one useful lesson using `agentos lesson add`.",
        "- Use `agentos research <url>` for one article you want saved.",
        "- Keep risky actions manual.",
        "",
        "## Notes",
        "",
        "- Add anything you want the system to remember below this line.",
        "",
    ]
    text = "\n".join(lines)
    out.write_text(text, encoding="utf-8")
    latest.write_text(text, encoding="utf-8")
    print(f"Wrote daily briefing: {out}")
    print(f"Updated latest daily briefing: {latest}")

if __name__ == "__main__":
    write_briefing()
